### ISSUE TITLE
local installation causes internal server error

### ISSUE THREAD

**Issue by tornography** [sitecake/sitecake#52] opened 2015-06-19 07:39 UTC
Hi, there is a problem when installing sitecake (2.2.8) an a local machine.

First, here is my setup
* Windows 7
* php 5.6.3
* Server on localhost:8080 (directory is ``D:\Workspace\sitecake\``)

After extracting sitecake and the example template, calling ``localhost:8080/sitecake.php`` causes this error in console.

```[Fri Jun 19 09:26:07 2015] ::1:49781 [500]: /sitecake.php - Uncaught exception 'InvalidArgumentException' with
message 'Identifier "filesystem.adapter" is not defined.' in D:\Workspace\sitecake\sitecake\2.2.8\server\vendor
\pimple\pimple\lib\Pimple.php:78
Stack trace:
#0 D:\Workspace\sitecake\sitecake\2.2.8\server\admin-full.php(43): Pimple->offsetGet('filesystem.adap...')
#1 D:\Workspace\sitecake\sitecake\2.2.8\server\admin.php(35): include('D:\\Workspace\\si...')
#2 D:\Workspace\sitecake\sitecake.php(1): include('D:\\Workspace\\si...')
#3 {main}
  thrown in D:\Workspace\sitecake\sitecake\2.2.8\server\vendor\pimple\pimple\lib\Pimple.php on line 78```

Calling ``localhost:8080/`` works as expected.

**Comment by PidaPan** [comment] 2015-06-19 11:55
This seems to be the same issue like in #50.

**Comment by sitecake** [comment] 2015-06-23 07:46
Yes, it is a duplicate of #50. Resolved and closed now.

**Closed by sitecake** 2015-06-23 07:46 UTC
